### ISSUE TITLE
Cannot repeat link process

### ISSUE THREAD

**Issue by Michael-Tanjuakio** [deotern/Plugswork#1]
I put the wrong Server Id and Secert Key and it disabled the plugin, when I found out the actual keys I went back to reload it and it will disable it with this message 
Notice: Array to string conversion in phar://C:/Users/namehere/Documents/PocketMine-MP/plugins/Plugswork_v1.php[EXPERIMENTAL].phar/src/Plugswork/Plugswork.php on line 74
- [Plugswork] api.openErrorArray[

**Comment by NIIP99** [comment]
@Mike4l6 
Thanks for reporting, you can change the Server ID and Secret Key by:
1) Delete the /Plugswork folder in /plugins folder
2) Start the server and it should ask you to fill in your ID and key again
3) And Plugswork will handle rest of the things, enjoy! :)

Btw, thanks for reporting, Plugswork is now released as EXPERIMENTAL, please report if you found any bugs in the plugin

**Comment by Michael-Tanjuakio** [comment]
Thanks I have deleted the PlugsWork Folder and entered the right code :D

**Comment by NIIP99** [comment]
Nice! :)
