### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by mikelees2** [deotern/Plugswork#11]
#### Issue description

 Loading Plugswork:  80 %
Notice: Undefined property: Plugswork\Plugswork::$listender in phar:///home/mike/Desktop/ImagicalMine/plugins/Plugswork_v5.php.bleed.phar/src/Plugswork/Plugswork.php on line 201
[18:54:37] critical> Error: "Call to a member function load() on null" (EXCEPTION) in "/Plugswork_v5.bleed.phar/src/Plugswork/Plugswork" at line 201
#### Extra Information

- Plugswork Version: 5.php
- MCPE Server Software: IM 1.4

**Comment by NIIP99** [comment]
@mikelees2 Fixed, please use 7.php.bleed. Thank you for report bug to us :)
