### ISSUE TITLE
Vote

### ISSUE THREAD

**Issue by Aericio** [deotern/Plugswork#13]
#### Issue description

Vote not working. 
#### Steps to reproduce the issue

Enable voting on server from website, setup all the things and yah
#### Extra Information

- Plugswork Version: v9.php.bleed
- MCPE Server Software: ClearSky php7 (no version, just says php7)
#### Crash dumps, backtrace or other files

```
Warning: Missing argument 2 for Plugswork\Utils\PwLang::translateConstant(), called in phar://C:/Users/user/Desktop/Plots/plugins/Plugswork.phar/src/Plugswork/Module/VoteModule.php on line 87 and defined in phar://C:/Users/user/Desktop/Plots/plugins/Plugswork.phar/src/Plugswork/Utils/PwLang.php on line 81

Notice: Undefined variable: name in phar://C:/Users/user/Desktop/Plots/plugins/Plugswork.phar/src/Plugswork/Utils/PwLang.php on line 90
[17:35:22] [Server thread/CRITICAL]: Could not execute task Plugswork\Task\AutoVoteTask: Call to undefined method Plugswork\Module\VoteModule::getServer()
[17:35:22] [Server thread/CRITICAL]: Error: "Call to undefined method Plugswork\Module\VoteModule::getServer()" (EXCEPTION) in "/Plugswork.phar/src/Plugswork/Module/VoteModule" at line 88

```

**Comment by remotevase** [comment]
Hey garre! Haven't seen you for a while! (Also, I do not believe that the vote feature was fully implemented yet

**Comment by Aericio** [comment]
Ohh... Okay then.

**Comment by remotevase** [comment]
Please note

> fully

It was implemented, just not fully

**Comment by kennethgomad02** [comment]
guys plugswork website down

**Comment by remotevase** [comment]
We know. This project was abandoned a while ago.

**Comment by Aericio** [comment]
Wonder if anyone is planning to revive this... probably not.

**Comment by k3ithos** [comment]
I don't think so... @deotern is usually busy with stuff anyway.

**Comment by NIIP99** [comment]
Plugswork has been discontinued due to low usability and users. Instead, I'm more on focusing JamAuth (https://github.com/deotern/JamAuth)

@keithkfng If you wanted to join, just let me know

**Comment by k3ithos** [comment]
@deotern Another project? Lol... Yeh I'll join.
