### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by DevIDFREBY** [deotern/Plugswork#16]
#### Issue description

When you start writing it incorrectly entered id or secret key, although put things right
#### Extra Information

- Plugswork Version: 9.php
- MCPE Server Software: ImagicalMine v1.4
#### Crash dumps, backtrace or other files

[13:30:58] system> Enabling Plugswork v9.php.bleed

  Loading Plugswork:  73 %
- [Plugswork] Open API Error Occured!
  ERROR: No Server ID or Secret Key is filled!
  
  Plugswork Data Checker
  IP:
  Registered:
  Version: 9.php.bleed

[13:31:09] system> Disabling Plugswork v9.php.bleed

**Comment by DevIDFREBY** [comment]
I translated by Google translator :D

**Comment by Aericio** [comment]
You didn't set it up correctly, thats why. Delete the Plugswork folder (not phar) and do it again. You need to put your Server ID that you get in the control panel in Plugswork

**Comment by daniktheboss** [comment]
What is the Web site? The one that I saw doesn't work!

**Comment by k3ithos** [comment]
This project has been suspended for now.
