### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mikelees2** [deotern/Plugswork#2]
[18:03:13] system> Enabling Plugswork v1.php

Warning: Invalid argument supplied for foreach() in phar:///home/mike/Desktop/ImagicalMine/plugins/Plugswork_v1.php[EXPERIMENTAL].phar/src/Plugswork/Utils/PwLang.php on line 28
[18:03:14] system> [Plugswork]

**Comment by NIIP99** [comment]
Seems like you did not fill in the messages at Control Panel, is it?

I will do a quick fix for this, but please fill in the messages at Control Panel. Otherwise, you'll see messages like this: api.openAPIError, etc

**Comment by mikelees2** [comment]
I think i am missing these files altogether on my side
Do you know where they should be located on my side?

**Comment by NIIP99** [comment]
No, you're not missing anything, you just need to login to Plugswork Control Panel, and go to:
Server > Server Settings > Message Editor > _Fill the messages form here_
:smiley:

**Comment by mikelees2** [comment]
Done. 
Now I still get no feedback from the server in the control panel. no stats.

**Comment by NIIP99** [comment]
Can you please try the v2.php.bleed build? See if it's fixed :)

**Comment by mikelees2** [comment]
Done.
My server says i have V2 your side says V1 Still no info from server.

**Comment by mikelees2** [comment]
OK I’m starting to get some activity. 
Its showing online status and active.
Also registering proper Plugswork ver.
Still no users showing and server load.

**Comment by NIIP99** [comment]
@mikeless2
Yep :) I have fixed the uptime fetcher, and showing online users will be added in v3 😆

**Comment by mikelees2** [comment]
Copy. Thanks

**Comment by mikelees2** [comment]
It looks like the uptime data cleared at midnight.

**Comment by mikelees2** [comment]
V3
Notice: Undefined offset: 6 in phar:///home/mike/Desktop/ImagicalMine/plugins/Plugswork_v3.php.bleed.phar/src/Plugswork/Task/BroadcastTask.php on line 76
[09:40:15] system> [Plugswork](Broadcast) 

Notice: Undefined property: Plugswork\Task\BroadcastTask::$i in phar:///home/mike/Desktop/ImagicalMine/plugins/Plugswork_v3.php.bleed.phar/src/Plugswork/Task/BroadcastTask.php on line 78
