### ISSUE TITLE
not connecting to server

### ISSUE THREAD

**Issue by bmlui** [deotern/Plugswork#5]
### OS and versions

- Plugswork: 2.php.bleed
- PHP: 7
- OS: Windows 10 genisys
### Crash dumps, backtrace or other files

Plugswork does not recognize that server is online

**Comment by NIIP99** [comment]
@biswarm22
Please make sure the IP you filled in is same as the IP you registered at Control Panel,

I will create new command `/pw check` in 3.php.bleed for you guys to check the server info and see if it's same with Control Panel to resolve your issue

**Comment by bmlui** [comment]
@deotern thanks
